# version: '3.8'
services:
  backend:
    container_name: cbv-todo
    build:
      context: ./core
    ports:
      - "8000:8000"
    volumes:
      - ./core:/app
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000