# Generated by Django 4.2 on 2025-05-28 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='updated_date',
            new_name='updated_at',
        ),
    ]
