# Generated by Django 4.2 on 2025-05-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_created_date_profile_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='updated_date',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='user',
            name='is_reset_token_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
