# Generated by Django 4.2 on 2025-05-29 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_created_at_profile_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_reset_token_used',
        ),
    ]
